### ISSUE TITLE
Amazing job, could you provide pretrained models?

### ISSUE THREAD

**Issue by yanghu819** [hukkai/no-residual-network#1]

**Comment by hukkai** [comment]
Unfortunately, I do not have plans to update this repo until our work is accepted. Once accepted, will let you know and provide pretrained models.

**Comment by yanghu819** [comment]
I reproduce your work, imagenet with conv kernel size 3x3 is 76% or so, but
with bigger kernel like 5 can achieve 77+%

Kai Hu ***@***.***> 于2022年2月4日周五 12:27写道：
